---

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  tags:
    - docker

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  tags:
    - docker


- name: Install list of packages
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'docker-ce', 'python3-pip']
    update_cache: yes
  tags:
    - docker


- name: Install docker-compose
  pip:
    name: docker-compose
  tags:
    - docker
